# runtime: python
# env: flex

# runtime_config:
#     python_version: 3
    
# manual_scaling:
#   instances: 1
# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10

# entrypoint: gunicorn -w 17 run:app


runtime: python37

# Remember - storing secrets in plaintext is potentially unsafe. Consider using
# something like https://cloud.google.com/kms/ to help keep secrets secret.
env_variables:
  CLOUD_SQL_CONNECTION_NAME: radiant-moon-270008:us-central1:bajandabase2
  DB_USER: postgres
  DB_PASS: choco
  DB_NAME: testing
